---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install PyMySQL
  apt:
    name: python3-pymysql
    state: present

- name: Install MySQL
  apt:
    name: mysql-server
    state: present

- name: Start MySQL service
  service:
    name: mysql
    state: started
    enabled: yes

- name: Check if MySQL root password is set
  shell: "mysqladmin -u root -p'{{ mysql_root_password }}' status"
  register: mysql_root_password_status
  ignore_errors: true

- name: Set password for root user via Unix socket
  mysql_user:
    name: root
    host: localhost
    password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    priv: '*.*:ALL,GRANT'
    state: present
  when: mysql_root_password_status.rc != 0

- name: Save root password in .my.cnf
  template:
    src: root_cnf.j2
    dest: /root/.my.cnf
    owner: root
    mode: '0600'

- name: Create database
  mysql_db:
    name: bright_ideas
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Create database user
  mysql_user:
    name: "{{ mysql_user_name }}"
    password: "{{ mysql_user_password }}"
    priv: 'bright_ideas.*:ALL'
    host: '%'
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Remove MySQL configuration file
  file:
    path: /root/.my.cnf
    state: absent
  become: true
